// AUTO-GENERATED from the Foundry PF1 system pack (weapons-and-ammo).
// All Paizo PF1e weapons with a standard NdD attack. dmgCount d dmgDie, crit range/mult,
// damage type (S/P/B), category (light/1h/2h/ranged), and weapon group.
const WEAPONS = [
  {"name":"Air Repeater","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Aklys","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Aldori Dueling Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Ankus","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"P","group":"bladesHeavy"},
  {"name":"Armor Spikes","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Axe Musket","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Barbazu Beard","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"close"},
  {"name":"Barbed Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"spears"},
  {"name":"Bardiche","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"S","group":"axes"},
  {"name":"Bastard Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Baston Fighting Stick","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Battle Aspergillum","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Battle Axe","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Battle Poi","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"F","group":"flails"},
  {"name":"Bayonet","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Bec de Corbin","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"B/P","group":"polearms"},
  {"name":"Bich'hwa","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":null},
  {"name":"Bill","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"polearms"},
  {"name":"Blade Boot","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Bladed Scarf","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"flails"},
  {"name":"Blowgun","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":2,"crit":20,"mult":2,"type":"P","group":"thrown"},
  {"name":"Blunderbuss","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B/P","group":"firearms"},
  {"name":"Bo Staff","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"double"},
  {"name":"Boar Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"P","group":"spears"},
  {"name":"Boarding Axe","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P/S","group":"axes"},
  {"name":"Boarding Gaff","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P/S","group":"double"},
  {"name":"Boarding Pike","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Brass Knife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Brass Knuckles","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"B","group":"close"},
  {"name":"Breech-Loader","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Broken-Back Seax","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"U","group":"bladesLight"},
  {"name":"Brutal Bola","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B/P","group":null},
  {"name":"Buckler Gun","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Butchering Axe","cat":"2h","ranged":false,"dmgCount":3,"dmgDie":6,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Butterfly Knife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Butterfly Sword","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Cat-o'-Nine-Tails","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"flails"},
  {"name":"Cestus","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"B/P","group":"close"},
  {"name":"Chain Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P/S","group":"double"},
  {"name":"Chain-Hammer","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"double"},
  {"name":"Chakram","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Claw Blades","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Club","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Coat Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Collapsible Kumade","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"axes"},
  {"name":"Combat Scabbard","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Composite Longbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Composite Shortbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Crook","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"polearms"},
  {"name":"Culverin","cat":"ranged","ranged":true,"dmgCount":2,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Cutlass","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Cylinder Rifle","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Dagger","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Dagger Pistol","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Dan Bong","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":19,"mult":2,"type":"B","group":"close"},
  {"name":"Deer Horn Knife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"P","group":"bladesLight"},
  {"name":"Dire Flail","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"double"},
  {"name":"Dogslicer","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Doru","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Double Chicken Saber","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Double Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Double Hackbut","cat":"ranged","ranged":true,"dmgCount":2,"dmgDie":12,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Double Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Double Walking Stick Katana","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Double-Barreled Musket","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":12,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Double-Barreled Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Double-Barreled Shotgun","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B/P","group":"firearms"},
  {"name":"Double-Chained Kama","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"double"},
  {"name":"Dragon Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Dragoon Musket","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":12,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Dragoon Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Drow Razor","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":18,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Dueling Dagger","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Dueling Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Dwarven Boulder Helmet","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B","group":"close"},
  {"name":"Dwarven Chain-Flail","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Dwarven Dorn-Dergar","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Dwarven Double Waraxe","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Dwarven Giant-Sticker","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":20,"mult":3,"type":"P/S","group":"polearms"},
  {"name":"Dwarven Heavy Axe-Gauntlet","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Dwarven Heavy Pelletbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":19,"mult":3,"type":"B","group":"crossbows"},
  {"name":"Dwarven Light Axe-Gauntlet","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Dwarven Light Pelletbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":19,"mult":3,"type":"B","group":"crossbows"},
  {"name":"Dwarven Longaxe","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":12,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Dwarven Longhammer","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Dwarven Maulaxe","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"B/S","group":"axes"},
  {"name":"Dwarven Ram Hammer","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Dwarven Sphinx Hammer","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Dwarven Urgrosh","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P/S","group":"double"},
  {"name":"Dwarven Waraxe","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Earth Breaker","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Elven Branched Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Elven Curve Blade","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Elven Leafblade","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":18,"mult":2,"type":"P/S","group":null},
  {"name":"Elven Thornblade","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"P/S","group":null},
  {"name":"Emei Piercer","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":19,"mult":2,"type":"P","group":"close"},
  {"name":"Estoc","cat":"1h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":18,"mult":2,"type":"P","group":"bladesHeavy"},
  {"name":"Falcata","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":3,"type":"S","group":"bladesHeavy"},
  {"name":"Falchion","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Fauchard","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":18,"mult":2,"type":"S","group":"polearms"},
  {"name":"Fiend's Mouth Cannon","cat":"ranged","ranged":true,"dmgCount":8,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":null},
  {"name":"Fighting Fan","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"P","group":"close"},
  {"name":"Fire Lance","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":4,"type":"P","group":"firearms"},
  {"name":"Flailpole","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Flambard","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Flask Pike","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Flickmace","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Flindbar","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B/P","group":"flails"},
  {"name":"Flying Blade","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":12,"crit":20,"mult":3,"type":"S","group":"flails"},
  {"name":"Flying Talon","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P/S","group":"flails"},
  {"name":"Frost Brand","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Gandasa","cat":"1h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Garrote","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"close"},
  {"name":"Gastraphetes","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":12,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Gauntlet","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"B","group":"close"},
  {"name":"Gladius","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Glaive","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"polearms"},
  {"name":"Glaive-Guisarme","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"polearms"},
  {"name":"Gnome Battle Ladder","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"double"},
  {"name":"Gnome Flick-Mace","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Gnome Hooked Hammer","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"B/P","group":"double"},
  {"name":"Gnome Pincher","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Gnome Piston Maul","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Gnome Ripsaw Glaive","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"polearms"},
  {"name":"Great Terbutje","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Greataxe","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":12,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Greatclub","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Greatsword","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Guisarme","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":3,"type":"S","group":"polearms"},
  {"name":"Halberd","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"P/S","group":"polearms"},
  {"name":"Halfling Rope-Shot","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Halfling Stitched Sling","cat":"1h","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Hanbo","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Hand Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Handaxe","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Harpoon","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Heavy Ballista","cat":"ranged","ranged":true,"dmgCount":4,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":null},
  {"name":"Heavy Crank Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Heavy Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Heavy Crossbow (Underwater)","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Heavy Flail","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"B","group":"flails"},
  {"name":"Heavy Mace","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Heavy Pick","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":4,"type":"P","group":"axes"},
  {"name":"Heavy Slaver's Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":1,"type":"B","group":"crossbows"},
  {"name":"Heavy Wrist Launcher","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P","group":null},
  {"name":"Hook Hand","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"close"},
  {"name":"Hooked Axe","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Hooked Lance","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"P","group":"polearms"},
  {"name":"Horse Bow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":null},
  {"name":"Horsechopper","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"P/S","group":null},
  {"name":"Hunga Munga","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Hurlbat","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P/S","group":"axes"},
  {"name":"Injection Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Iron Brush","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Javelin","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"spears"},
  {"name":"Jutte","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"monk"},
  {"name":"Kama","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Kasatha Spinal Sword","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P/S","group":null},
  {"name":"Katana","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Kerambit","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":3,"type":"S","group":"bladesLight"},
  {"name":"Khopesh","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Knobkerrie","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Knuckle Axe","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Kobold Tail Attachment (Long Lash)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":null},
  {"name":"Kobold Tail Attachment (Pounder)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Kobold Tail Attachment (Razored)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":null},
  {"name":"Kobold Tail Attachment (Spiked)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":null},
  {"name":"Kobold Tail Attachment (Sweeper)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Kukri","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":18,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Kumade","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"axes"},
  {"name":"Kunai","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B/P","group":"thrown"},
  {"name":"Kusarigama","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"B/S","group":"double"},
  {"name":"Kyoketsu Shoge","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P/S","group":"flails"},
  {"name":"Lance","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Lantern Staff","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Lawrence 1917 Flamethrower","cat":"ranged","ranged":false,"dmgCount":4,"dmgDie":6,"crit":20,"mult":2,"type":"F","group":"firearms"},
  {"name":"Light Ballista","cat":"ranged","ranged":true,"dmgCount":3,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":null},
  {"name":"Light Bombard","cat":"ranged","ranged":true,"dmgCount":5,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":null},
  {"name":"Light Crank Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Light Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Light Crossbow (Underwater)","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Light Flail","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Light Hammer","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Light Mace","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Light Pick","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":4,"type":"P","group":"axes"},
  {"name":"Light Slaver's Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":19,"mult":1,"type":"B","group":"crossbows"},
  {"name":"Light Trebuchet","cat":"ranged","ranged":true,"dmgCount":4,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":null},
  {"name":"Lizard King War Trident","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"P","group":null},
  {"name":"Longbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Longspear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Longsword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Lucerne Hammer","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":12,"crit":20,"mult":2,"type":"B/P","group":"polearms"},
  {"name":"Lungchuan Tamo","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P/S","group":"monk"},
  {"name":"Machete","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Madsen Light Machine Gun","cat":"ranged","ranged":true,"dmgCount":2,"dmgDie":6,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Mancatcher","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":2,"crit":20,"mult":1,"type":"P","group":"polearms"},
  {"name":"Manople","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Mattock","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":4,"type":"P","group":"axes"},
  {"name":"Maxim M1910 Machine Gun","cat":"ranged","ranged":true,"dmgCount":2,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Mere Club","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B/P","group":"close"},
  {"name":"Meteor Hammer","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Monk's Spade","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B/P/S","group":"double"},
  {"name":"Morningstar","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B/P","group":"flails"},
  {"name":"Mosin-Nagant M1891 Rifle","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Musket","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":12,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Nagant M1895 Revolver","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Naginata","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"S","group":"polearms"},
  {"name":"Nine-Ring Broadsword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"bladesHeavy"},
  {"name":"Nine-Section Whip","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"B","group":"flails"},
  {"name":"Nodachi","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":18,"mult":2,"type":"P/S","group":"bladesHeavy"},
  {"name":"Nunchaku","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"flails"},
  {"name":"Ogre Hook","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"P","group":"polearms"},
  {"name":"Orc Double Axe","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"S","group":"axes"},
  {"name":"Orc Hornbow","cat":"ranged","ranged":true,"dmgCount":2,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Orc Skull Ram","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"B","group":"spears"},
  {"name":"Paddle-Foot Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Pata","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"axes"},
  {"name":"Pepperbox","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Pepperbox Rifle","cat":"ranged","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Pickaxe","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"P","group":null},
  {"name":"Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Planson","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B/P","group":"hammers"},
  {"name":"Punching Dagger","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"P","group":"close"},
  {"name":"Quadrens","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Quarterstaff","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"double"},
  {"name":"Radium Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Radium Rifle","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Ranseur","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":3,"type":"P","group":"polearms"},
  {"name":"Rapier","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Ratfolk Tailblade","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Reaver's Scythe","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":19,"mult":4,"type":"P/S","group":"bladesHeavy"},
  {"name":"Reflex Bow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Repeating Hand Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Repeating Heavy Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Repeating Light Crossbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Revolver","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Rhoka Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Rhomphaia","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":3,"type":"P/S","group":null},
  {"name":"Rifle","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Rope Gauntlet","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"U","group":"close"},
  {"name":"Sai","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"B","group":"monk"},
  {"name":"Sanpkhang","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"Sansetsukon","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"B","group":"flails"},
  {"name":"Sap","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"close"},
  {"name":"Sarissa","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Sawtoothed Sabre","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Scimitar","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Scizore","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Scorpion Whip","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"flails"},
  {"name":"Scythe","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":4,"type":"P/S","group":"bladesHeavy"},
  {"name":"Sea-Knife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Seven-Branched Sword","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"S","group":"bladesHeavy"},
  {"name":"Shang Gou","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"monk"},
  {"name":"Sharpened Combat Scabbard","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Shield Spikes (Heavy)","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Shield Spikes (Light)","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Shortbow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":"bows"},
  {"name":"Shortspear","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"spears"},
  {"name":"Shortsword","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Shotel","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"bladesHeavy"},
  {"name":"Shotgun","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"B/P","group":"firearms"},
  {"name":"Siangham","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"monk"},
  {"name":"Sibat","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P/S","group":"spears"},
  {"name":"Sica","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Sickle","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Sickle-Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Spear-Sling","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Spider-Leg Sickle","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":null},
  {"name":"Spiked Chain","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"flails"},
  {"name":"Spiked Gauntlet","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Spiral Rapier","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"P","group":null},
  {"name":"Split-Blade Sword","cat":"1h","ranged":false,"dmgCount":2,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Spring Blade","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P/S","group":null},
  {"name":"Starknife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"P","group":"bladesLight"},
  {"name":"Steel Terbutje","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":null},
  {"name":"Stonebow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"crossbows"},
  {"name":"Switchblade Knife","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Switchscythe","cat":"2h","ranged":false,"dmgCount":2,"dmgDie":4,"crit":20,"mult":4,"type":"P/S","group":"bladesHeavy"},
  {"name":"Sword Cane","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":"bladesLight"},
  {"name":"Sword Cane Pistol","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":20,"mult":3,"type":"B/P","group":"firearms"},
  {"name":"Swordbreaker Dagger","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Syringe Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"P","group":"spears"},
  {"name":"Taiaha","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":2,"type":"B/P","group":"double"},
  {"name":"Tailblade","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Tekko-Kagi","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Temple Sword","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Tepoztopilli","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":19,"mult":2,"type":"P/S","group":null},
  {"name":"Terbutje","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"bladesHeavy"},
  {"name":"Tetsubo","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B","group":"hammers"},
  {"name":"Thark Rifle","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":10,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Thorn Bow","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":6,"crit":20,"mult":3,"type":"P","group":null},
  {"name":"Thorn Bracer","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"P","group":null},
  {"name":"Throwing Axe","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"S","group":"axes"},
  {"name":"Tiger Fork","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"P","group":"monk"},
  {"name":"Tonfa","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"close"},
  {"name":"Tongi","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":19,"mult":3,"type":"P","group":"axes"},
  {"name":"Totem Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"B/P","group":"spears"},
  {"name":"Traveling Kettle","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"monk"},
  {"name":"Tri-Bladed Katar","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":4,"type":"P","group":"bladesHeavy"},
  {"name":"Tri-Point Double-Edged Sword","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":10,"crit":20,"mult":3,"type":"P","group":"monk"},
  {"name":"Trident","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":2,"type":"P","group":"spears"},
  {"name":"Tube Arrow Shooter","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"crossbows"},
  {"name":"Two-Bladed Sword","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":19,"mult":2,"type":"S","group":"double"},
  {"name":"Urumi","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":18,"mult":2,"type":"S","group":"flails"},
  {"name":"Wahaika","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":6,"crit":20,"mult":2,"type":"B","group":"hammers"},
  {"name":"Wakizashi","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"P/S","group":"bladesLight"},
  {"name":"War Razor","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":19,"mult":2,"type":"S","group":"bladesLight"},
  {"name":"Warhammer","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"B","group":"hammers"},
  {"name":"Warhammer Musket","cat":"ranged","ranged":true,"dmgCount":1,"dmgDie":8,"crit":20,"mult":4,"type":"B/P","group":"firearms"},
  {"name":"Waveblade","cat":"light","ranged":false,"dmgCount":1,"dmgDie":6,"crit":18,"mult":2,"type":"P/S","group":"close"},
  {"name":"Weighted Spear","cat":"2h","ranged":false,"dmgCount":1,"dmgDie":8,"crit":20,"mult":3,"type":"B/P","group":"double"},
  {"name":"Whip","cat":"1h","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"S","group":"flails"},
  {"name":"Wooden Stake","cat":"light","ranged":false,"dmgCount":1,"dmgDie":4,"crit":20,"mult":2,"type":"P","group":"close"},
  {"name":"Wushu Dart","cat":"light","ranged":false,"dmgCount":1,"dmgDie":3,"crit":20,"mult":2,"type":"P","group":"close"},
];
const WEAPON_BY_NAME = Object.fromEntries(WEAPONS.map(w => [w.name.toLowerCase(), w]));
module.exports = { WEAPONS, WEAPON_BY_NAME };
